packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  '@ark/schema': patches/@ark__schema.patch
