import { defineConfig } from 'vite-plus'

export default defineConfig({
	defaultPackage: './packages/renderer',
	lint: {
		plugins: [
			'react',
			'typescript',
			'unicorn',
			'eslint',
			'oxc',
			'import',
			'promise',
		],
		categories: {
			correctness: 'error',
			suspicious: 'error',
			pedantic: 'allow',
			perf: 'error',
			style: 'allow',
			restriction: 'allow',
		},
		env: {
			builtin: true,
			es2022: true,
			browser: true,
			node: true,
		},
		ignorePatterns: [
			'dist/*',
			'**/dm.d.ts',
			'**/dm.js',
			'**/dist/**',
			'**/build/**',
			'**/node_modules/**',
			'**/dist-electron/**',
			'**/release/**',
			'**/*.config.mjs',
			'**/*.js',
			'**/worker-configuration.d.ts',
			'**/package-lock.json',
			'**/pnpm-lock.yaml',
		],
		options: {
			typeAware: true,
			typeCheck: false,
		},
		rules: {
			'react/react-in-jsx-scope': 'off',
			'no-unused-vars': [
				'error',
				{
					args: 'all',
					argsIgnorePattern: '^_',
					caughtErrors: 'all',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					ignoreRestSiblings: true,
				},
			],
			'no-console': ['error', { allow: ['error', 'warn'] }],
			'react-hooks/exhaustive-deps': 'allow',
			'typescript/no-explicit-any': 'allow',
			'typescript/no-misused-promises': ['error', { checksVoidReturn: false }],
			'typescript/no-unsafe-type-assertion': 'allow',
			'typescript/consistent-return': 'off',
			'no-underscore-dangle': [
				'error',
				{ allow: ['__csrf', '__dirname', '__filename'] },
			],
			'react/no-unstable-nested-components': 'off',
			'react/no-array-index-key': 'allow',
			'import/no-unassigned-import': 'allow',
			'unicorn/require-module-specifiers': 'allow',
			'unicorn/prefer-add-event-listener': 'allow',
			'eslint/no-await-in-loop': 'error',
			'eslint/no-shadow': 'allow',
			'eslint/preserve-caught-error': 'allow',
			'promise/no-callback-in-promise': 'allow',
			'typescript/no-floating-promises': 'allow',
			'typescript/no-unnecessary-type-conversion': 'allow',
			'always-return': 'allow',
			'no-array-sort': 'allow',
			'no-new-array': 'allow',
			'style-prop-object': 'allow',
			'no-map-spread': 'allow',
			'no-await-in-loop': 'allow',
		},
		settings: {
			react: {
				version: '19.2',
			},
		},
		overrides: [
			{
				files: ['packages/**/*.{ts,tsx,js,jsx}'],
				rules: {
					'no-console': 'allow',
				},
			},
			{
				files: [
					'**/vite.config.ts',
					'**/*.config.ts',
					'**/*.config.mts',
					'packages/main/scripts/**',
				],
				rules: {
					'no-console': 'allow',
				},
			},
		],
	},
	fmt: {
		printWidth: 80,
		tabWidth: 2,
		useTabs: true,
		semi: false,
		singleQuote: true,
		jsxSingleQuote: true,
		quoteProps: 'as-needed',
		trailingComma: 'all',
		bracketSpacing: true,
		bracketSameLine: false,
		arrowParens: 'always',
		endOfLine: 'lf',
		singleAttributePerLine: true,
		ignorePatterns: [
			'**/dm.d.ts',
			'**/dm.js',
			'**/worker-configuration.d.ts',
			'dist/**',
			'**/dist/**',
			'**/dist-electron/**',
			'**/release/**',
		],
		sortPackageJson: true,
		sortImports: {
			groups: [
				['side_effect'],
				['builtin'],
				['external', 'type-external'],
				['internal', 'type-internal'],
				['parent', 'type-parent'],
				['sibling', 'type-sibling'],
				['index', 'type-index'],
			],
		},
	},
	staged: {
		'*': 'vp check --fix',
	},
	test: {
		environment: 'node',
		include: ['packages/**/*.test.ts'],
		exclude: [
			'**/node_modules/**',
			'**/dist/**',
			'**/dist-electron/**',
			'**/release/**',
		],
	},
})
